name: wasteagram
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  firebase_storage: ^3.1.3
  image_picker: 0.6.3+4
  cloud_firestore: ^0.13.4
  json_annotation: ^3.0.1
  location: ^2.5.0
  built_value:
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.8.0
  json_serializable: ^3.2.5
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
