name: dart_space_adventure
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0
  convert: ^2.1.1
  string_validator: ^0.1.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
